global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:5555']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:5556']