pipeline {
  agent any

  environment {
    IMAGE_NAME = 'walidazhari/product-service'
    SHORT_COMMIT = "${env.GIT_COMMIT.take(7)}"
    IMAGE_TAG = "${env.BUILD_NUMBER}-${env.GIT_COMMIT.take(7)}"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          dockerImage = docker.build("${IMAGE_NAME}:${IMAGE_TAG}")
        }
      }
    }

    stage('Trivy Security Scan') {
      steps {
        sh '''
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:0.50.1 image ${IMAGE_NAME}:${IMAGE_TAG}
        '''
      }
    }

    stage('Login to Docker Hub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
        }
      }
    }

    stage('Push to Docker Hub') {
      steps {
        script {
          dockerImage.push("${IMAGE_TAG}")
          dockerImage.push("latest")
        }
      }
    }
  }

  post {
    always {
      cleanWs()
    }
  }
}